### ISSUE TITLE
Order confirmation page is blank

### ISSUE THREAD

**Issue by nuzelac** [coingate/prestashop-plugin#2]
Hi,

I am testing Prestashop 1.6.0.14 with latest Coingate module (v1.2.7). Everything works ok except that order confirmation page when returning back from Coingate is blank. 

![potvrda narudzbe - uzi shop 2018-01-02 21-32-07](https://user-images.githubusercontent.com/195299/34499029-780dec6e-f004-11e7-8b60-6a4538a7b35a.png)

I'm not an experienced Prestashop developer, so I'm wondering if this is the expected behavior. From the simple comparison with the default cashondelivery module, it seems to me that coingate.php is registering the payment return hook, but never actually implementing the method and displaying some template?

https://github.com/coingate/prestashop-plugin/blob/373681b746f328d23a7f22dd71a799b1a1a81e96/modules/coingate/coingate.php#L185

https://github.com/PrestaShop/cashondelivery/blob/9c32f582d4fb00fcc136ba5d2a51cfbe54d8ecd6/cashondelivery.php#L111-L117

Thanks!

**Comment by vgumonis** [comment]
That you for your input.
We updated our confirmation page.
