### ISSUE TITLE
Front ContextErrorException

### ISSUE THREAD

**Issue by backamblock** [coingate/prestashop-plugin#4]
Hello, i have an error when debug mode on and trying to make a coingate payment
i think this is why my payments do not get confirmed automatically.
this are the errors from the page:

(1/1) ContextErrorExceptionWarning: A non-numeric value encountered
--
in redirect.php line 119

at CoingateRedirectModuleFrontController->generateToken(9)
in redirect.php line 51

at CoingateRedirectModuleFrontController->initContent()
in Controller.php line 255

at ControllerCore->run()
in Dispatcher.php line 428

at DispatcherCore->dispatch()
in index.php line 28

please tell me how to fix it or make an update.. thanks

my prestashop is 1.7.4.2 and php 7.2 but this error is existent in 1.7.4.1 as well

greetings

**Comment by vgumonis** [comment]
Hi, 
We recently made a new release of our plugin. To fix this particular issue please update your plugin.
